name: Deploy to PythonAnywhere

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:        ${{ secrets.PA_HOST }}
          username:    ${{ secrets.PA_USER }}
          key:         ${{ secrets.PA_SSH_PRIVATE_KEY }}
          script: |
            cd ~/JUSCA-QA-PORTFOLIO
            echo "Pulling latest changes from GitHub"
            git pull origin main
            echo "Done pulling latest changes from GitHub"

            echo "Restarting the web app"
            touch /var/www/jusca_pythonanywhere_com_wsgi.py
            echo "Web app restarted"
            echo "Deployed at $(date)"